version: '2.1'
services:
  sisventas.authentication:    
    container_name: sisventas_authentication_ms
    image: duvaninho/sisventas_authentication_ms:1.0
    environment:
      - ConnectionString= Server= sisventas.authentication.data;User=sa;Password=Pass@word;DataBase=SisVentasAuthentication;
      - LdapParameters:OrganizationalUnit=sa
      - LdapParameters:Domain=arqsoft.unal.edu.co
      - LdapParametersConnection:Host=arqsoft.unal.edu.co
      - LdapParametersConnection:Port=389
    ports:
      - "5004:80"
    depends_on:
      - sisventas.authentication.data
  
  sisventas.authentication.data:
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    container_name: sisventas_authentication_db
    environment: 
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1434:1433"
    